package farmaciaweb.Models;
// Generated 22/11/2014 09:20:01 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private String sobrenome;
     private Integer idade;
     private String cidade;
     private String bairro;
     private String rua;
     private Integer numero;
     private String telefone;
     private String loginCliente;
     private String senha;
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);

    public Clientes() {
    }

	
    public Clientes(int codigo) {
        this.codigo = codigo;
    }
    public Clientes(int codigo, String nome, String sobrenome, Integer idade, String cidade, String bairro, String rua, Integer numero, String telefone, String loginCliente, String senha, Set<Pedidos> pedidoses) {
       this.codigo = codigo;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.idade = idade;
       this.cidade = cidade;
       this.bairro = bairro;
       this.rua = rua;
       this.numero = numero;
       this.telefone = telefone;
       this.loginCliente = loginCliente;
       this.senha = senha;
       this.pedidoses = pedidoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public Integer getIdade() {
        return this.idade;
    }
    
    public void setIdade(Integer idade) {
        this.idade = idade;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getLoginCliente() {
        return this.loginCliente;
    }
    
    public void setLoginCliente(String loginCliente) {
        this.loginCliente = loginCliente;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }




}


