package farmaciaweb.Models;
// Generated 22/11/2014 09:20:01 by Hibernate Tools 3.6.0



/**
 * DetalhesPedido generated by hbm2java
 */
public class DetalhesPedido  implements java.io.Serializable {


     private DetalhesPedidoId id;
     private Pedidos pedidos;
     private Produtos produtos;
     private long precoUnitario;
     private int quantidade;

    public DetalhesPedido() {
    }

    public DetalhesPedido(DetalhesPedidoId id, Pedidos pedidos, Produtos produtos, long precoUnitario, int quantidade) {
       this.id = id;
       this.pedidos = pedidos;
       this.produtos = produtos;
       this.precoUnitario = precoUnitario;
       this.quantidade = quantidade;
    }
   
    public DetalhesPedidoId getId() {
        return this.id;
    }
    
    public void setId(DetalhesPedidoId id) {
        this.id = id;
    }
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }
    public long getPrecoUnitario() {
        return this.precoUnitario;
    }
    
    public void setPrecoUnitario(long precoUnitario) {
        this.precoUnitario = precoUnitario;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }




}


