package farmaciaweb.Models;
// Generated 22/11/2014 09:20:01 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedores generated by hbm2java
 */
public class Fornecedores  implements java.io.Serializable {

     private int codigo;
     private String nome;
     private String cidade;
     private String bairro;
     private String rua;
     private Integer numero;
     private String telefone;
     private Set<Produtos> produtoses = new HashSet<Produtos>(0);

    public Fornecedores() {
    }

	
    public Fornecedores(int codigo) {
        this.codigo = codigo;
    }
    public Fornecedores(int codigo, String nome, String cidade, String bairro, String rua, Integer numero, String telefone, Set<Produtos> produtoses) {
       this.codigo = codigo;
       this.nome = nome;
       this.cidade = cidade;
       this.bairro = bairro;
       this.rua = rua;
       this.numero = numero;
       this.telefone = telefone;
       this.produtoses = produtoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Set<Produtos> getProdutoses() {
        return this.produtoses;
    }
    
    public void setProdutoses(Set<Produtos> produtoses) {
        this.produtoses = produtoses;
    }




}


